name: Test Action

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request:
    branches-ignore:
      - "release/*"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prepare Node.js and Yarn
        uses: actions/setup-node@v3
